w11/d01/recipe/recipe/config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'
  resources :entries

end

w11/d01/recipe/recipe/app/models/entry.rb
class Entry < ActiveRecord::Base
end

w11/d01/recipe/recipe/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

w11/d01/recipe/recipe/app/controllers/entries_controller.rb
class EntriesController < ApplicationController

	skip_before_filter  :verify_authenticity_token

	def index
		@entries = Entry.all
		respond_to do |format|
			format.html { render :index }
			format.json { render json: @entries }
		end
  	end




  	def new
  		@entry = Entry.new
 	end

	def create
	  @entry = Entry.create(entry_params)
	  redirect_to @entry
	end


	def show
		@entry = Entry.find_by(id: params[:id])
	end


	def destroy
		@entry = Entry.find_by(id: params[:id])
		@entry.destroy
		redirect_to entries_path
	end

	def edit
		@entry = Entry.find_by(id: params[:id])
	end

	def update
		@entry = Entry.find_by(id: params[:id])
		@entry.update_attributes(entry_params)
		redirect_to @entry
	end


	private
	  def entry_params
	  params.require(:entry).permit(:name, :ingredients, :instructions)
	end




end

w11/d01/recipe/recipe/app/helpers/application_helper.rb
module ApplicationHelper
end

w11/d01/recipe/recipe/app/views/entries/edit.html.erb
<%= form_for @entry, url: {action: 'update'} do |f| %>
<%= f.label :name %>
<%= f.text_field :name, value: @entry.name %>
<br /><br />

<%= f.label :ingredients %>
<%= f.text_field :ingredients, value: @entry.ingredients %>
<br /><br />

<%= f.label :instructions %>
<%= f.text_area :instructions, value: @entry.instructions %>
<br /><br />

<%= f.submit %>
<% end %>
<%= link_to 'cancel', @entry %>

w11/d01/recipe/recipe/app/views/entries/index.html.erb
  <h1>Welcome to my food blog!</h1>

  <% @entries.each do |entry| %>

<h2><%= link_to entry.name, entry_path(entry)%></h2>
  <h4>Ingredients</h4>
  <h3><%= entry.ingredients %></h3>
  <p><%= entry.instructions%></p>
  <% end %>

  <%= link_to 'Create a new entry!', new_entry_path %>

w11/d01/recipe/recipe/app/views/entries/new.html.erb
  <%= form_for @entry, url: {action: 'create'} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br /><br />

  <%= f.label :ingredients %>
  <%= f.text_field :ingredients %>
  <br /><br />

  <%= f.label :instructions %>
  <%= f.text_area :instructions %>
  <br /><br />

  <%= f.submit %>
  <% end %>

  <%= link_to 'cancel', entries_path %>

w11/d01/recipe/recipe/app/views/entries/show.html.erb
<h2><%= @entry.name %></h2>
<h4>Ingredients</h4>
<h3><%= @entry.ingredients %></h3>
<p><%= @entry.instructions%></p>

<%= link_to 'delete', @entry, method: :delete %>
<%= link_to 'back', entries_path %>
<%= link_to 'edit', edit_entry_path(@entry) %>