w11/d01/newspaper_json/config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'

  resources :articles 
  resources :authors
  

end

w11/d01/newspaper_json/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
end

w11/d01/newspaper_json/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
end

w11/d01/newspaper_json/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

w11/d01/newspaper_json/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @articles.map { |article|  
        Hash[article.id, Hash["headline", article.headline, 
          "content", article.content, "author", article.author.name]]  } }
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article= Article.create(article_params)
    redirect_to article_path(@article)
  end

  def show
    @article = Article.find_by(id: params[:id])
  end

  def destroy
    @article = Article.find_by(id: params[:id])
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find_by(id: params[:id])
  end

  def update
    @article = Article.find_by(id: params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end


  private
    def article_params
      params.require(:article).permit(:headline, :content, :photo_url)
    end


end

w11/d01/newspaper_json/app/helpers/application_helper.rb
module ApplicationHelper
end

w11/d01/newspaper_json/app/views/articles/edit.html.erb
<%= form_for @article, url: {action: 'update'} do |f|%>
  <%= f.label :headline%>
  <%= f.text_field :headline, value: @article.headline %>
  <br>
  <%= f.label :content%>
  <%= f.text_area :content, value: @article.content %>
  <br>
  <%= f.label :photo_url%>
  <%= f.text_field :photo_url, value: @article.photo_url %>
  <br>
  <%= f.submit %>
<% end %>

w11/d01/newspaper_json/app/views/articles/index.html.erb
<html>
  <head>
    <title></title>
  </head>
  <body>

<h1>Welcome to my newspaper!</h1>

<div class="container-fluid">
    <% @articles.each do |article| %>
  <div class= "row">
  <div class = "col-md-6 col-md-offset-3">
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#<%=article.id%>" aria-expanded="false" aria-controls="collapseExample">
    <%=article.headline%>
    </button>
    <div class="collapse" id="<%=article.id%>">
      <div class="well">
      <%= link_to article.headline, article_path(article) %>
      <br>
      <%= link_to article.author.name, author_path(article.author) %>
      <br>
      <%= article.content %>
      <br>
      <img class="img-circle" <%= image_tag article.photo_url, height:300%> >
      <br>
      </div>
    </div>
    </div>
    </div>

    <% end %>


</div>

  </body>
</html>

w11/d01/newspaper_json/app/views/articles/new.html.erb
<%= form_for @article, url: {action: 'create'} do |f|%>
  <%= f.label :headline%>
  <%= f.text_field :headline%>
  <br>
  <%= f.label :content%>
  <%= f.text_area :content%>
  <br>
  <%= f.label :photo_url%>
  <%= f.text_field :photo_url%>
  <br>
  <%= f.submit %>
<% end %>

w11/d01/newspaper_json/app/views/articles/show.html.erb
<%= @article.headline %>
<br>
<%= @article.author.name %>
<br>
<%= @article.content %>
<br>
<img class="img-circle" <%= image_tag @article.photo_url, height:300%> >
<br>
<%= link_to "Destroy!!!", article_path(@article), method: :delete %>
<br>
<%= link_to "Go home!", articles_path %>
<%= link_to "Edit", edit_article_path(@article)%>

w11/d01/newspaper_json/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newspaper</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>